name: srp_tomo 
channels: !!python/tuple
- conda-forge
- defaults
dependencies:
- conda-forge::ipython
- conda-forge::jupyter
- conda-forge::matplotlib
- conda-forge::python
- conda-forge::setuptools
- conda-forge::numpy
- conda-forge::scipy
- conda-forge::h5py

